Yubbyshoes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/', include('store.urls', namespace='store')),
    path('', include('pages.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('__debug__/', include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'
urlpatterns = [
    path('', views.index, name='index'),
    path('shop/', views.shop, name='shop'),
    path('shop/women', views.shop_women, name='shop_women'),
    path('shop/item/<int:pk>', views.item_detail, name='item_detail'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('shop/item/<int:pk>/buy', views.buy, name='buy'),
]

store/urls.py
from django.urls import path
from .views import (Create, Detail, Update, Delete,
                    filter_products_bycategory, Orders, OrderStatusUpdateView, customers_view, customers_update)

app_name = 'store'
# store/
urlpatterns = [
    # path('', store, name='store'),
    path('create/', Create.as_view(), name="create"),
    # path('list/', List.as_view(), name="list"),
    path('filter/<str:category>/', filter_products_bycategory, name="filter"),
    path('detail/<int:pk>/', Detail.as_view(), name="detail"),
    path('update/<int:pk>/', Update.as_view(), name='update'),
    path('delete/<int:pk>/', Delete.as_view(), name='delete'),
    path('orders/', Orders.as_view(), name='orders'),
    path('customers/', customers_view, name='customers'),
    path('orders/<int:pk>/update/', OrderStatusUpdateView.as_view(),
         name='order-status-update'),
    path('customers/update/<int:pk>/', customers_update,
         name='customers_update'),
]

store/models.py
from django.db import models
from accounts.models import Customer


class Category(models.Model):
    category_name = models.CharField(max_length=20)
    category_initials = models.CharField(max_length=3)
    date_added = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.category_name


class Company(models.Model):
    company_name = models.CharField(max_length=100)
    company_initials = models.CharField(max_length=5)
    date_added = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.company_name


class Product(models.Model):
    name = models.CharField(max_length=200)
    price = models.FloatField(default=0.00)
    discounted_price = models.FloatField(null=True, blank=True)
    image = models.ImageField(null=True, blank=True,
                              upload_to='media/products')
    date_added = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    is_new_arrival = models.BooleanField(default=False)
    in_stock = models.IntegerField(default=0)
    product_model = models.CharField(max_length=10, unique=True)
    category = models.ForeignKey(
        Category, on_delete=models.PROTECT)
    company = models.ForeignKey(
        Company, on_delete=models.CASCADE)

    def __str__(self):
        return self.product_model + '-' + self.name

    def save(self, *args, **kwargs):
        super().save()
        from PIL import Image
        original_img = Image.open(self.image.path)
        width, height = original_img.size
        if (width < height):
            x = 0
            y = (height - width) / 2
            cropped_img = original_img.crop((x, y, width + x, width + y))
        else:
            x = (width - height) / 2
            y = 0
            cropped_img = original_img.crop((x, y, height + x, height + y))
        cropped_img.save(self.image.path)


class OrderItem(models.Model):
    STATUS_CHOICES = (
        ('PR', 'Processing'),
        ('SH', 'Shipping'),
        ('DE', 'Delivered'),
    )
    ordered_on = models.DateTimeField(auto_now_add=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE,
                                related_name='orders')
    customer = models.ForeignKey(Customer, on_delete=models.PROTECT)
    order_email = models.CharField(max_length=255, blank=True, null=True)
    order_quantity = models.IntegerField()
    order_status = models.CharField(max_length=3, choices=STATUS_CHOICES,
                                    default='PR')

    def __str__(self):
        return f"{self.product.name}"

store/forms.py
from django import forms
from accounts.models import Customer
from .models import Product, OrderItem


class ProductInfoModelForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'price', 'discounted_price',
                  'image', 'in_stock', 'product_model', 'category', 'company', 'is_new_arrival']


class OrderStatusUpdateForm(forms.ModelForm):
    # order_status = forms.CharField(widget=forms.Select(attrs={}))

    class Meta:
        model = OrderItem
        fields = ['order_status', ]

    def save(self, commit=True):
        prev_status = OrderItem.objects.get(pk=self.instance.id).order_status
        if self.instance.product.in_stock > 0:
            if prev_status == 'PR':
                self.instance.product.in_stock -= self.instance.order_quantity
                self.instance.product.save()
        return super().save()


class CustomerUpdateForm(forms.ModelForm):
    # order_status = forms.CharField(widget=forms.Select(attrs={}))

    class Meta:
        model = Customer
        fields = ['default_size', ]

    def save(self, commit=True):
        print(type(self.instance.default_size))
        self.instance.default_size = str(self.cleaned_data.get("default_size"))
        self.instance.save()
        # prev_status = OrderItem.objects.get(pk=self.instance.id).order_status
        # if self.instance.product.in_stock > 0:
        #     if prev_status == 'PR':
        #         self.instance.product.in_stock -= self.instance.order_quantity
        #         self.instance.product.save()
        return super().save()

store/views.py
from django.shortcuts import render, reverse, redirect, get_list_or_404
from django.urls import reverse_lazy
from django.views.generic import (CreateView, ListView, DetailView, UpdateView,
                                  DeleteView)
from .forms import ProductInfoModelForm, OrderStatusUpdateForm, CustomerUpdateForm
from .models import Product, Category, OrderItem
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.decorators.http import require_http_methods
from accounts.models import Customer


@method_decorator(login_required, name='dispatch')
class Create(CreateView):
    form_class = ProductInfoModelForm
    template_name = 'store/create.html'

    def get_success_url(self):
        return reverse('store:filter', args=['All'])


@method_decorator(login_required, name='dispatch')
class Detail(DetailView):
    template_name = 'store/detail.html'
    context_object_name = 'product'
    model = Product


@method_decorator(login_required, name='dispatch')
class Update(UpdateView):
    form_class = ProductInfoModelForm
    model = Product
    template_name = 'store/update.html'

    def get_success_url(self):
        return reverse('store:filter', args=['All'])


@method_decorator(login_required, name='dispatch')
class Delete(DeleteView):
    model = Product

    def get_success_url(self):
        return reverse('store:filter', args=['All'])


@login_required()
def filter_products_bycategory(request, category):
    if category == 'All' or category == 'all':
        products = Product.objects.all()
    else:
        products = Product.objects.filter(
            category__category_name__contains=category)
    return render(request, 'store/list.html', context={
        'data': products,
        "category": Category.objects.all()
    })


@method_decorator(login_required, name='dispatch')
class Orders(ListView):
    template_name = 'store/order.html'
    model = OrderItem
    context_object_name = 'orders'

    def get_queryset(self):
        return self.model.objects.all().order_by('-ordered_on')

    def get_context_data(self, *, object_list=None, **kwargs):
        data = super().get_context_data()
        data['update_form'] = OrderStatusUpdateForm()
        return data


@login_required()
@require_http_methods(["GET"])
def customers_view(request):
    customers = Customer.objects.all()
    pn = request.GET.get('phone_number')

    if pn:
        customers = get_list_or_404(Customer, phone_number=int(pn))
    return render(request, 'store/customer.html', context={
        'customers': customers,
        'shoe_sizes': [39, 40, 41, 42, 43]
    })


@login_required()
@require_http_methods(["POST"])
def customers_update(request, pk):
    customer = Customer.objects.get(id=pk)
    form = CustomerUpdateForm(request.POST, instance=customer)
    # customer.default_size =
    if form.is_valid():
        print("form is valid")
        print(form.cleaned_data)
        form.save()
    return redirect("store:customers")
#     # pn = request.GET.get('phone_number')

#     # if pn:
#     #     customers = get_object_or_404(Category, phone_number=pn)
#     #     # print(products)

#     return render(request, 'store/customer.html', context={
#         'customers': customers,
#         'sizes': [39, 40, 41, 42, 43]
#     })
# @method_decorator(login_required, name='dispatch')
# class CustomerUpdateView(UpdateView):
#     template_name = 'store/customer.html'
#     success_url = reverse_lazy('store:customers')
#     form_class = CustomerUpdateForm

#     def get_queryset(self):
#         return Customer.objects.all()


@method_decorator(login_required, name='dispatch')
class OrderStatusUpdateView(UpdateView):
    template_name = 'store/order.html'
    success_url = reverse_lazy('store:orders')
    form_class = OrderStatusUpdateForm

    def get_queryset(self):
        return OrderItem.objects.all()

    # def form_valid(self, form):
    #     print(self.object.product)
    #     print(self.object.product.in_stock)
    #     print(self.object.order_status)
    #     if self.object.product.in_stock > 0:
    #         if self.object.order_status == 'PR':
    #             self.object.product.in_stock -= self.object.order_quantity
    #
    #     return super().form_valid(form)

    # def post(self, request, *args, **kwargs):
    #     self.object = self.get_object()
    #
    #     form = self.get_form()
    #     if form.is_valid():
    #         if self.object.product.in_stock > 0:
    #             if self.object.order_status == 'SH':
    #                 self.object.product.in_stock -= self.object.order_quantity
    #
    #                 self.object.product.save()
    #         return self.form_valid(form)
    #     else:
    #         return self.form_invalid(form)

store/templates/store/create.html
{% extends "store/store-base.html" %} {% load crispy_forms_tags %}

{% block store_title %}
  Create |
{% endblock store_title %}

{% block main-content %}
  <div class="row">
    <div class="container-fluid">
      <div class="col-12 col-md-6 offset-md-1">
        <h1 class="text-uppercase pb-3 pt-4">Add Product</h1>
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %} {{ form|crispy }}
          <button type="submit" class="btn btn-primary float-right
        btn-lg">Submit
          </button>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

store/templates/store/customer.html
{% extends 'store/store-base.html' %}
{% load to_str %}
<!-- #fdfd -->
{% block store_title %} Customers | {%endblock store_title %}
<!-- sdfsd -->
{% block main-content %}
<h1>Customers</h1>
<form action="{% url 'store:customers' %}?phone_number=phone_number"   class="form-inline my-2 my-lg-0">
  <input name="phone_number"  class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
</form>
<table class="table table-striped table-responsive-xl">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Phone NUmber</th>
      <th scope="col">Address</th>
      <th scope="col">Size</th>

      <!-- <th scope="col">Quantity</th>
          <th scope="col">Price</th>
          <th scope="col">Contact</th>
          <th scope="col">Client</th>
          <th scope="col">Client Email</th>
          <th scope="col">Address</th>
          <th scope="col">Status</th>
          <th scope="col">Action</th> -->
    </tr>
  </thead>

  <tbody>
    {% for cust in customers %}
    <tr>
      <td>{{ cust.name }}</td>
      <td>{{ cust.phone_number }}</td>
      <td>{{ cust.address }}</td>
      <td><form action="{% url 'store:customers_update' cust.id %}" method="POST">
        {% csrf_token %}
        <div class="form-row align-items-center">
          <div class="col-auto my-1">
            <label class="mr-sm-2 sr-only" for="inlineFormCustomSelect">Preference</label>
            <select name = 'default_size' class="custom-select mr-sm-2" id="inlineFormCustomSelect">
                {% for size in shoe_sizes %}
                {% if cust.default_size == size|to_str%}
                <option selected value={{size}}>{{size}}</option>
                {% else %}
                <option value={{size}}>{{size}}</option>
                {% endif %}
                {% endfor %}
            </select>
          </div>
          <div class="col-auto my-1">
            <button type="submit" class="btn btn-primary">Submit</button>
          </div></form>
        </td> 
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock main-content %}

store/templates/store/customers.html
{% extends 'store/store-base.html' %} {% block store_title %} Customers | {%
endblock store_title %} {% block main-content %}
<h1>Customers</h1>
<table class="table table-striped table-responsive-xl">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Phone NUmber</th>
      <!-- <th scope="col">Quantity</th>
      <th scope="col">Price</th>
      <th scope="col">Contact</th>
      <th scope="col">Client</th>
      <th scope="col">Client Email</th>
      <th scope="col">Address</th>
      <th scope="col">Status</th>
      <th scope="col">Action</th> -->
    </tr>
  </thead>

  <tbody>
    {% for cust in customers %}
    <tr>
      <th scope="row">{{ cust.id }}</th>
      <td>{{ cust.name }}</td>

      <td>{{ cust.phone_number }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock main-content %}

store/templates/store/detail.html
{% extends "store/store-base.html" %}
{% load static %}

{% block store_title %}
  {{ product.name }} |
{% endblock store_title %}

{% block main-content %}
  <div class="container-fluid">
    <div class="col-12 col-md-6 offset-2">
      <h6>Detail</h6>
      <div>
        <img src="{{ product.image.url }}" alt="" class="w-50">
      </div>
      <h3 class="text-success">{{ product.name }}</h3>

      <p>Price :{{ product.price }}</p>
      {% if product.discounted_price %}
        Discounted_price :{{ product.discounted_price }}
      {% endif %}

      <p>Date :{{ product.date_modified }}</p>

      <p>Model :{{ product.product_model }}</p>
      <div class="btn-group">

        <!-- Button trigger modal -->
        <button type="button" class="btn btn-danger" data-toggle="modal"
                data-target="#exampleModal">
          Delete
        </button>

        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog"
             aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal"
                        aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                Are you sure you want to delete?
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary"
                        data-dismiss="modal">Close
                </button>
                <a href="{% url 'store:delete' product.id %}" class="btn
      btn-danger">Delete</a>
              </div>
            </div>
          </div>
        </div>

        <a href="{% url 'store:update' product.id %}" class="btn
      btn-success">Update</a>
      </div>
    </div>


  </div>
{% endblock %}

store/templates/store/list.html
{% extends "store/store-base.html" %}

{% block store_title %}
  Products |
{% endblock store_title %}

{% block main-content %}
  <h1>List of all Products</h1>


  <ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link
{% if 'All' in request.path or 'all' in request.path %} active{% endif %}"
         href="{% url 'store:filter' 'All' %}">All</a>
    </li>
    {% for cat in category %}
      <li class="nav-item">
        <a class="nav-link {% if cat.category_name in request.path %} active
    {% endif %}"
           href="{% url 'store:filter' cat %}">
          {{ cat }}</a>
      </li>
    {% endfor %}

  </ul>

  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Product Name</th>
        <th scope="col">In Stock</th>
        <th scope="col">Price</th>
        <th scope="col">Product Model</th>
        <th scope="col">Action</th>
      </tr>
      </thead>

      <tbody>
      {% for u in data %}
        <tr>
          <th scope="row">{{ u.id }}</th>
          <td>
            {% if u.image %}
              <img src="{{ u.image.url }}" alt="product_image"
                   class="rounded-circle mr-2"
                   height="30"
                   width="30"
              >
            {% endif %}
            {{ u.name }}</td>
          <td>{{ u.in_stock }}</td>
          <td>{{ u.price }}</td>
          <td>{{ u.product_model }}</td>
          <td>
            <a href="{% url 'store:detail' u.id %}">Detail</a> /
            <a href="{% url 'store:update' u.id %}">Update</a> /
            <form action="/store/delete/{{ u.id }}/" class="d-inline-block"
                  method="post" id="formdelete{{ u.id }}">
              {% csrf_token %}
              <a href="#"
                 onclick="document.getElementById('formdelete{{ u.id }}')
                     .submit()"
              >Delete</a
              >
            </form>
          </td>
        </tr>
      {% endfor %}
      </tbody>

    </table>
  </div>

{% endblock %}

store/templates/store/order.html
{% extends 'store/store-base.html' %}
{% load multiply %}

{% block store_title %}
  Orders |
{% endblock store_title %}

{% block main-content %}
  <h1>Orders</h1>
  <table class="table table-striped table-responsive-xl">
    <thead>
    <tr>
      <th scope="col">OrderID</th>
      <th scope="col">Product</th>
      <th scope="col">Quantity</th>
      <th scope="col">Price</th>
      <th scope="col">Contact</th>
      <th scope="col">Client</th>
      <th scope="col">Client Email</th>
      <th scope="col">Address</th>
      <th scope="col">Status</th>
      <th scope="col">Action</th>
    </tr>
    </thead>

    <tbody>
    {% for order in orders %}
      <tr>
        <th scope="row">{{ order.id }}</th>
        <td><img src="{{ order.product.image.url }}" alt="product_image"
                 class="rounded-circle mr-2"
                 height="30"
                 width="30"
        >{{ order.product.name }}</td>
        <td>{{ order.order_quantity }}</td>
        <td>{{ order.product.price|multiply:order.order_quantity }}</td>
        <td>{{ order.customer.phone_number }}</td>

        <td>{{ order.customer.name }}</td>
        <td>{% if order.order_email %}
          {{ order.order_email }}
        {% else %}
          --
        {% endif %}</td>
        <td class='address-tab'>{{ order.customer.address }}</td>
        <td>{{ order.get_order_status_display }}</td>
        <td>
          <div onclick="openAction({{ order.id }})" class="change-action"
               id="change-{{ order.id }}">
            Change
          </div>
          <div id="form-{{ order.id }}" style="display:none">
            <form action="{% url 'store:order-status-update' pk=order.id %}"
                {#                  class="d-inline-block"#}
                  method="post" id="formDelete{{ order.id }}">
              {% csrf_token %}
              {% for field in update_form %}
                {{ field.errors }}
                <select name="{{ field.name }}">
                  {% for choice in field.field.choices %}
                    <option value="{{ choice.0 }}"
                        {% if choice.0 == order.order_status %}
                            selected
                        {% endif %}
                    >{{ choice.1 }}</option>
                  {% endfor %}
                </select>
              {% endfor %}
              <br>
              <a href="#"
                 onclick=
                     "document.getElementById('formDelete{{ order.id }}').submit()"
              >Update</a
              >
              <a href="#" class="text-muted"
                 onclick=
                     "closeAction({{ order.id }})"
              >Cancel</a>
            </form>
          </div>
        </td>
      </tr>
    {% endfor %}
    </tbody>

  </table>
{% endblock main-content %}

{% block scripts %}
  <script>
      function openAction(actionId) {
          document.getElementById('change-' + actionId).style.display = 'none';
          document.getElementById('form-' + actionId).style.display = 'block';
      }

      function closeAction(actionId) {
          document.getElementById('change-' + actionId).style.display = 'block';
          document.getElementById('form-' + actionId).style.display = 'none';
      }
  </script>
{% endblock scripts %}

store/templates/store/store-base.html
{% extends 'base.html' %}
{% load static %}

{% block styles %}
  <link rel="stylesheet" href="{% static 'store/css/main.css' %}">
  <link rel="stylesheet" href="{% static 'css/font-awesome.css' %}">
  <style>
    .store-tagline {
        color: #c4dce8;
    }
  </style>
{% endblock styles %}

{% block title %}
  {% block store_title %}{% endblock store_title %}Store |
{% endblock title %}

{% block content %}

  <div class="container-fluid row p-0 m-0 store-wrapper">
    <div class="col-lg-2 p-0 m-0 d-none d-lg-block">
      {% include 'store/utils/sidebar.html' %}
    </div>
    <div id="sidebar-responsive" class="responsive d-block d-lg-none">
      <div class="responsive-sidebar-wrapper">
        <div class="menu-wrapper" id="menu-wrapper" onclick="toggleSidebar()">
          <span class="fa fa-bars text-white fa-2x" id="menu-bar-icon"></span>
          <span class="fa fa-close text-white fa-2x"
                id="close-menu-icon"></span>
        </div>
        {% include 'store/utils/sidebar.html' %}
      </div>
    </div>
    <div class="content-wrapper col-12 col-lg-10 p-0 m-0">
      {% block main-content %}
      {% endblock %}
    </div>
  </div>

  <script>
      const sidebar = document.getElementById('sidebar-responsive');
      const menuBarIcon = document.getElementById('menu-bar-icon');
      const closeMenuIcon = document.getElementById('close-menu-icon');
      const menuWrapper = document.getElementById('menu-wrapper');

      let isOpen = false;

      menuBarIcon.style.display = 'block';
      closeMenuIcon.style.display = 'none';

      const toggleSidebar = () => {
          if (isOpen) {
              console.log('close')
              sidebar.classList.remove('open');
              menuBarIcon.style.display = 'block';
              closeMenuIcon.style.display = 'none';
              menuWrapper.classList.remove('open');
              isOpen = !isOpen;
          } else {
              console.log('open')
              sidebar.classList.add('open');
              menuBarIcon.style.display = 'none';
              closeMenuIcon.style.display = 'block';
              menuWrapper.classList.add('open');
              isOpen = !isOpen;
          }
      }
  </script>

{% endblock content %}

store/templates/store/update.html
{% extends "store/store-base.html" %} {% load crispy_forms_tags %}

{% block store_title %}
  Update |
{% endblock store_title %}

{% block main-content %}
  <div class="row">
    <div class="container-fluid">
      <div class="col-12 col-md-6 offset-md-1">
        <h1>Update Details</h1>
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %} {{ form|crispy }}
          <button type="submit"
                  class="btn btn-primary float-right btn-lg">
            Submit
          </button>
        </form>
      </div>
    </div>
  </div>
{% endblock %}