Yubbyshoes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/', include('store.urls', namespace='store')),
    path('', include('pages.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('__debug__/', include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'
urlpatterns = [
    path('', views.index, name='index'),
    path('shop/', views.shop, name='shop'),
    path('shop/women', views.shop_women, name='shop_women'),
    path('shop/item/<int:pk>', views.item_detail, name='item_detail'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('shop/item/<int:pk>/buy', views.buy, name='buy'),
]

pages/templates/pages/buy.html
{% extends 'pages/page_base.html' %}

{% block title %}
  Buy-{{ product.name }} |
{% endblock title %}

{% block content %}
  <!-- mian-content -->
  <div class="main-banner inner" id="home">
    {% include 'pages/utils/nav.html' %}
  </div>
  <!--//main-content-->
  <!---->
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a href="{% url 'pages:index' %}">Home</a>
    </li>
    <li class="breadcrumb-item active">Buy Item</li>
  </ol>
  <!---->
  <!--// mian-content -->

  <!-- OrderPlacement Alert -->
  {% if is_ordered %}
    <div class="container mt-4">
      <div class="alert alert-success" role="alert">
        <h4 class="alert-heading">Order Placed!</h4>
        <p class="text-dark">Your Order has successfully been placed! You will
          get a call from
          our management team soon for order verification and sizes.</p>
        <hr>
        <p class="mb-0 text-dark"><strong>Thank you</strong> for shopping
          with us! Keep shopping Visit shop <a href=
                                                  "{% url 'pages:shop' %}">from here.
          &rarr;</a>
        </p>
      </div>
    </div>
  {% endif %}
  <!-- // OrderPlacement Alert -->

  <!-- banner -->
  <section class="ab-info-main py-5">
    <div class="container py-3">
      <h3 class="tittle text-center">Item Details</h3>
      <div class="row mx-auto mb-5">
        <div class="desc1-left col-md-4 offset-md-2">
          <img src='{{ product.image.url }}' class="img-fluid"
               alt="">
        </div>
        <div class="desc1-right col-md-5 pl-lg-5">
          <h3 class="text-uppercase">{{ product.name }}</h3>
          <h5>Rs. {{ product.price }} <span>
                              {% if product.discounted_price %}
                                {{ product.discounted_price }}
                              {% endif %}
                            </span></h5>
          <div class="available mt-3">
            <span>{% if product.in_stock > 0 %}
              In Stock: {{ product.in_stock }}
            {% else %}
              <strong>Out of Stock</strong>
            {% endif %}</span>
            <p>Lorem Ipsum has been the industry's standard since the 1500s.
              Praesent ullamcorper dui turpis.. </p>
          </div>

        </div>
      </div>
      <h3 class="tittle text-center" id="fill-details">
        <span class="sub-tittle">Contact
              Us</span> Fill Details</h3>
      <div class="row contact-main-info mt-5">
        <div class="col-md-6 contact-right-content mx-auto">
          <form action="{% url 'pages:buy' product.id %}" method="post">
            {% csrf_token %}
            {% for field in buy_detail_form %}
              {{ field.errors }}
              {{ field }}
            {% endfor %}
            <div class="read mt-3">
              <input type="submit" value="Submit">
            </div>
          </form>
        </div>

      </div>
    </div>
  </section>


  <!-- //contact -->
  {% include 'pages/utils/footer.html' %}
{% endblock content %}

pages/templates/pages/contact.html
{% extends 'pages/page_base.html' %}

{% block title %}
  Contact |
{% endblock title %}

{% block content %}
  <!-- mian-content -->
    <div class="main-banner inner" id="home">
        {% include 'pages/utils/nav.html' %}
    </div>
    <!--//main-content-->
    <!---->
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="index.html">Home</a>
        </li>
        <li class="breadcrumb-item active">Contact Us</li>
    </ol>
    <!---->
    <!--// mian-content -->
    <!-- banner -->
    <section class="ab-info-main py-5">
        <div class="container py-3">
            <h3 class="tittle text-center"><span
                class="sub-tittle">Find
              Us</span> Contact Us</h3>
            <div class="row contact-main-info mt-5">
                <div class="col-md-6 contact-right-content">
                    <form action="#" method="post">
                        <input type="text" name="Name" placeholder="Name" required="">
                        <input type="email" class="email" name="Email" placeholder="Email" required="">
                        <input type="text" name="Phone no" placeholder="Phone" required="">
                        <textarea name="Message" placeholder="Message" required=""></textarea>
                        <div class="read mt-3">
                            <input type="submit" value="Submit">
                        </div>
                    </form>
                </div>
                <div class="col-md-6 contact-left-content">
                    <div class="address-con">
                        <h4 class="mb-2"><span class="fa fa-phone-square" aria-hidden="true"></span> Phone</h4>
                        <p>+121 098 8907 9987</p>
                        <p>+121 098 8907 9987</p>
                    </div>
                    <div class="address-con my-4">
                        <h4 class="mb-2"><span class="fa fa-envelope-o" aria-hidden="true"></span> Email </h4>
                        <p><a href="mailto:info@example.com">info@example.com</a></p>
                        <p><a href="mailto:info@example.com">info@example.com</a></p>
                    </div>
                    <div class="address-con mb-4">
                        <h4 class="mb-2"><span class="fa fa-fax" aria-hidden="true"></span> Fax</h4>

                        <p>(800) 123-80088</p>
                    </div>
                    <div class="address-con">
                        <h4 class="mb-2"><span class="fa fa-map-marker" aria-hidden="true"></span> Location </h4>

                        <p>Honey Avenue, New York City</p>
                    </div>

                </div>

            </div>
            <div class="map-fo mt-lg-5 mt-4">

              <iframe src="https://maps.google.com/maps?q=butwal%20khushi%20complex&t=&z=13&ie=UTF8&iwloc=&output=embed" allowfullscreen></iframe>





            </div>
        </div>
    </section>


    <!-- //contact -->
    {% include 'pages/utils/footer.html' %}
  <script>
      addEventListener("load", function () {
          setTimeout(hideURLbar, 0);
      }, false);

      function hideURLbar() {
          window.scrollTo(0, 1);
      }
  </script>
{% endblock content%}

pages/templates/pages/index.html
{% extends 'pages/page_base.html' %}
{% load static %}

{% block content %}
  <!-- mian-content -->
  <div class="main-banner" id="home">
    <!-- header -->
    <header class="header">
      <div class="container-fluid px-lg-5">
        <!-- nav -->
        <nav class="py-2">
          <div id="logo">
            <h1><a href="{% url 'pages:index' %}" class="pt-1">
              <img src="{% static 'core/logo/pages_logo.svg' %}"
                   height="60"
                   alt="KhusiShoes">
            </a>
            </h1>
          </div>

          <label for="drop" class="toggle mt-3">Menu</label>
          <input type="checkbox" id="drop"/>
          <ul class="menu mt-2 pt-3">
            <li class="active"><a href="index.html">Home</a></li>
            <li><a href={% url 'pages:shop' %}>Men</a></li>
            <li><a href={% url 'pages:shop_women' %}>Women</a></li>
            <li><a href={% url 'pages:about' %}>About</a></li>
            <li><a href={% url 'pages:contact' %}>Contact</a></li>
          </ul>
        </nav>
        <!-- //nav -->
      </div>
    </header>
    <!-- //header -->
    <!--/banner-->
    <div class="banner-info">
      <h3 class="mb-4">Shop <br>
        Casual Shoes for Men and Women</h3>
      <div class="ban-buttons">
        <a href="{% url 'pages:shop' %}" class="btn">For Men</a>
        <a href="{% url 'pages:shop_women' %}" class="btn active">For Women</a>
      </div>
    </div>
    <!--// banner-inner -->

  </div>
  <!--//main-content-->
  <!--/ab -->
  <section class="about py-md-5 py-5">
    <div class="container-fluid">
      <div class="feature-grids row px-3">
        <div class="col-lg-3 gd-bottom">
          <div class="bottom-gd row">
            <div class="icon-gd col-md-3 text-center"><span class="fa fa-truck"
                                                            aria-hidden="true"></span>
            </div>
            <div class="icon-gd-info col-md-9">
              <h3 class="mb-2">FREE SHIPPING</h3>
              <p>On all order over $2000</p>
            </div>
          </div>
        </div>
        <div class="col-lg-3 gd-bottom">
          <div class="bottom-gd row bottom-gd2-active">
            <div class="icon-gd col-md-3 text-center"><span
                class="fa fa-bullhorn"
                aria-hidden="true"></span>
            </div>
            <div class="icon-gd-info col-md-9">
              <h3 class="mb-2">FREE RETURN</h3>
              <p>On 1st exchange in 30 days</p>
            </div>
          </div>
        </div>
        <div class="col-lg-3 gd-bottom">
          <div class="bottom-gd row">
            <div class="icon-gd col-md-3 text-center"><span class="fa fa-gift"
                                                            aria-hidden="true"></span>
            </div>

            <div class="icon-gd-info col-md-9">
              <h3 class="mb-2">MEMBER DISCOUNT</h3>
              <p>Register & save up to $29%</p>
            </div>

          </div>
        </div>
        <div class="col-lg-3 gd-bottom">
          <div class="bottom-gd row">
            <div class="icon-gd col-md-3 text-center"><span class="fa fa-usd"
                                                            aria-hidden="true"></span>
            </div>
            <div class="icon-gd-info col-md-9">
              <h3 class="mb-2">PREMIUM SUPPORT</h3>
              <p>Support 24 hours per day</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- //ab -->
  <!--/ab -->

  <!--Category -->
  <section class="container bg-grey p-3">
    <h3 class="mb-3 text-uppercase">Categories</h3>
    <ul class="d-flex flex-wrap py-0">
      {% for category in categories %}
        <li class="d-flex flex-wrap py-1 px-1">
          <a href="{% url 'pages:shop' %}?category={{ category.id }}"
             class="text-capitalize chip"
             id="underline-link"
          >{{ category.category_name }}</a>
        </li>
      {% endfor %}
    </ul>
  </section>
  <!-- //Category -->

  <section class="about py-5">
    <div class="container pb-lg-3">
      <h3 class="tittle text-center">New Arrivals</h3>
      <div class="row">
        {% for product in products %}
          <div class="col-md-4 product-men">
            <div class="product-shoe-info shoe text-center">
              <div class="men-thumb-item">
                {% if product.image %}
                  <a href="{% url 'pages:item_detail' product.id %}">
                    <img src="{{ product.image.url }}" class="img-fluid" alt="">
                  </a>
                {% endif %}
                <span class="product-new-top">New</span>
              </div>
              <div class="item-info-product">
                <h4>
                  <a href="{% url 'pages:item_detail' product.id %}"
                  >{{ product.name }}</a>
                </h4>

                <div class="product_price">
                  <div
                      class="grid-price text-center">
                    <span class="money pl-4">Rs. {{ product.price }}</span>
                  </div>
                  <div>
                    <a href="{% url 'pages:item_detail' product.id %}"
                       class="fancy-button secondary">View</a>
                    <a href="{% url 'pages:buy' product.id %}#fill-details"
                       class="fancy-button">Buy</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
      <div class="row">
        <div class="col-12 text-center mt-4">
          <a href="{% url 'pages:shop' %}" class="text-center fancy-button">
            Visit Our Shop <span>&rarr;</span>
          </a>
        </div>
      </div>
    </div>
  </section>
  <!-- //ab -->
  <!--/testimonials-->
  <section class="testimonials py-5">
    <div class="container">
      <div class="test-info text-center">
        <h3 class="my-md-2 my-3">Jenifer Burns</h3>

        <ul class="list-unstyled w3layouts-icons clients">
          <li>
            <a href="#">
              <span class="fa fa-star"></span>
            </a>
          </li>
          <li>
            <a href="#">
              <span class="fa fa-star"></span>
            </a>
          </li>
          <li>
            <a href="#">
              <span class="fa fa-star"></span>
            </a>
          </li>
          <li>
            <a href="#">
              <span class="fa fa-star-half-o"></span>
            </a>
          </li>
        </ul>
        <p><span class="fa fa-quote-left"></span> Lorem Ipsum has been the
          industry's standard since the 1500s. Praesent ullamcorper dui
          turpis.Nulla pellentesque mi non laoreet eleifend. Integer porttitor
          mollisar lorem, at molestie arcu pulvinar ut. <span
              class="fa fa-quote-right"></span></p>

      </div>
    </div>
  </section>
  <!--//testimonials-->
  <!--/ab -->
  <section class="about py-5">
    <div class="container pb-lg-3">
      <h3 class="tittle text-center">Popular Products</h3>
      <div class="row">
        <div class="col-md-6 latest-left">
          <div class="product-shoe-info shoe text-center">
            <img src="{% static 'images/img1.jpg' %}" class="img-fluid" alt="">
            <div class="shop-now"><a href="{% url 'pages:shop' %}" class="btn">Shop
              Now</a>
            </div>
          </div>
        </div>
        <div class="col-md-6 latest-right">
          <div class="row latest-grids">
            <div class="latest-grid1 product-men col-12">
              <div class="product-shoe-info shoe text-center">
                <div class="men-thumb-item">
                  <img src="{% static 'images/img2.jpg' %}" class="img-fluid"
                       alt="">
                  <div class="shop-now"><a href="{% url 'pages:shop' %}"
                                           class="btn">Shop
                    Now</a></div>
                </div>
              </div>
            </div>
            <div class="latest-grid2 product-men col-12 mt-lg-4">
              <div class="product-shoe-info shoe text-center">
                <div class="men-thumb-item">
                  <img src="{% static 'images/img3.jpg' %}" class="img-fluid"
                       alt="">
                  <div class="shop-now">
                    <a href="{% url 'pages:shop' %}" class="btn">
                      Shop Now
                    </a></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- //ab -->
  <!-- brands -->
  <section class="brands py-5" id="brands">
    <div class="container py-lg-0">
      <div class="row text-center brand-items">
        <div class="col-sm-2 col-3">
          <a href="#"><span class="fa fa-connectdevelop"
                            aria-hidden="true"></span></a>
        </div>
        <div class="col-sm-2 col-3">
          <a href="#"><span class="fa fa-empire" aria-hidden="true"></span></a>
        </div>
        <div class="col-sm-2 col-3">
          <a href="#"><span class="fa fa-ioxhost" aria-hidden="true"></span></a>
        </div>
        <div class="col-sm-2 col-3">
          <a href="#"><span class="fa fa-first-order"
                            aria-hidden="true"></span></a>
        </div>
        <div class="col-sm-2 col-3 mt-sm-0 mt-4">
          <a href="#"><span class="fa fa-joomla" aria-hidden="true"></span></a>
        </div>
        <div class="col-sm-2 col-3 mt-sm-0 mt-4">
          <a href="#"><span class="fa fa-dropbox" aria-hidden="true"></span></a>
        </div>
      </div>
    </div>
  </section>
  <!-- brands -->
  {% include 'pages/utils/footer.html' %}
  <script>
      const colors = ['5e72e4', '0eafcc', '0da5c0', '2dce89', 'fb6340', 'f5365c',
          '27272C', '1f38c5', 'B1210C'];
      const getRandomColor = () => {
          return colors[Math.floor(Math.random() * colors.length)]
      }
      window.onload = () => {
          const chips = document.querySelectorAll('.chip')
          for (let i = 0; i < chips.length; i++) {
              chips[i].style.backgroundColor = '#' + getRandomColor();
          }
      }
  </script>
  <script>
      addEventListener("load", function () {
          setTimeout(hideURLbar, 0);
      }, false);

      function hideURLbar() {
          window.scrollTo(0, 1);
      }
  </script>
{% endblock content %}

pages/templates/pages/shop-single.html
{% extends 'pages/page_base.html' %}

{% block title %}
  {{ product.name }} |
{% endblock title %}

{% block content %}
  <!-- main-content -->
  <div class="main-banner inner" id="home">
    {% include 'pages/utils/nav.html' %}

  </div>
  <!--//main-content-->
  <!-- Breadcrumb -->
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a href="{% url 'pages:index' %}">Home</a>
    </li>
    <li class="breadcrumb-item">
      <a href="{% url 'pages:shop' %}">Shop</a>
    </li>
    <li class="breadcrumb-item active">{{ product.name }}</li>
  </ol>
  <!-- //Breadcrumb -->
  <!-- banner -->
  <section class="ab-info-main py-md-5 py-4">
    <div class="container py-md-3">
      <!-- top Products -->
      <div class="row">
        <!-- product left -->
        <div class="side-bar col-lg-3">
          <!--preference -->
          <div class="left-side my-4">
            <h3 class="sear-head d-flex justify-content-between"><span
                class="text-uppercase">Occasion</span><span
                class="text-muted">Filter</span></h3>
            <ul class="w3layouts-box-list">
              {% for category in categories %}
                <li
                >
                  <a href="{% url 'pages:shop' %}?category={{ category.id }}"
                     class="text-muted"
                  >
                    <span class="span text-capitalize">
                      {{ category.category_name }}
                    </span>
                  </a>
                </li>
              {% endfor %}
            </ul>
          </div>
          <!-- // preference -->


        </div>
        <!-- //product left -->
        <!-- product right -->
        <div class="left-ads-display col-lg-9">
          <div class="row">
            <div class="desc1-left col-md-6">
              <img src='{{ product.image.url }}' class="img-fluid"
                   alt="">
            </div>
            <div class="desc1-right col-md-6 pl-lg-4">
              <h3 class="text-uppercase">{{ product.name }}</h3>
              <h5>Rs. {{ product.price }} <span>
                              {% if product.discounted_price %}
                                {{ product.discounted_price }}
                              {% endif %}
                            </span></h5>
              <div class="available mt-3">
                <span class="text-uppercase">
                  {% if product.in_stock > 0 %}
                    In Stock: {{ product.in_stock }}
                  {% else %}
                    <strong>Out Of Stock</strong>
                  {% endif %}
                </span>
                <p>Lorem Ipsum has been the industry's standard since the 1500s.
                  Praesent ullamcorper dui turpis.. </p>
              </div>
              <div>
                <a class="fancy-button" id="buy-link"
                   href="{% url 'pages:buy' product.id %}#fill-details">Buy</a>
              </div>
            </div>
          </div>
          <div class="row sub-para-w3layouts mt-5">

            <h3 class="shop-sing">Lorem ipsum dolor sit amet</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing
              elPellentesque vehicula augue eget nisl ullamcorper, molestie
              blandit ipsum auctor. Mauris volutpat augue dolor.Consectetur
              adipisicing elit, sed do eiusmod tempor incididunt ut lab ore et
              dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
              exercitation ullamco. labore et dolore magna aliqua.</p>
            <p class="mt-3 italic-blue">Consectetur adipisicing elPellentesque
              vehicula augue eget nisl ullamcorper, molestie blandit ipsum
              auctor. Mauris volutpat augue dolor.Consectetur adipisicing elit,
              sed do eiusmod tempor incididunt ut lab ore et dolore magna
              aliqua. Ut enim ad minim veniam, quis nostrud exercitation
              ullamco. labore et dolore magna aliqua.</p>
            <p class="mt-3">Lorem ipsum dolor sit amet, consectetur adipisicing
              elPellentesque vehicula augue eget nisl ullamcorper, molestie
              blandit ipsum auctor. Mauris volutpat augue dolor.Consectetur
              adipisicing elit, sed do eiusmod tempor incididunt ut lab ore et
              dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
              exercitation ullamco. labore et dolore magna aliqua.</p>
          </div>

          <h3 class="shop-sing">Featured Products</h3>
          <div class="row m-0">
            {% for p in featured_products %}
              <div class="col-md-4 product-men">
                <div class="product-shoe-info shoe text-center">
                  <div class="men-thumb-item">
                    {% if p.image %}
                      <a href="{% url 'pages:item_detail' p.id %}">
                        <img src='{{ p.image.url }}' class="img-fluid" alt="">
                      </a>
                    {% endif %}
                    <span class="product-new-top">New</span>
                  </div>
                  <div class="item-info-product">
                    <h4>
                      <a href="{% url 'pages:item_detail' p.id %}"
                      >{{ p.name }}</a>
                    </h4>

                    <div class="product_price">
                      <div class="grid-price">
                        <span class="money">Rs. {{ p.price }}</span>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- //contact -->
  {% include 'pages/utils/footer.html' %}
  <script>
      addEventListener("load", function () {
          setTimeout(hideURLbar, 0);
      }, false);

      function hideURLbar() {
          window.scrollTo(0, 1);
      }
  </script>
{% endblock content %}

pages/templates/pages/shop.html
{% extends 'pages/page_base.html' %}
{% load to_str %}

{% block title %}
  {% if 'women' in request.path %}
    Women's Shop |
  {% else %}
    Men's Shop |
  {% endif %}
{% endblock title %}

{% block content %}


  <!-- mian-content -->
  <div class="main-banner inner" id="home">
    {% include 'pages/utils/nav.html' %}

  </div>
  <!--//main-content-->
  <!---->
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a href="{% url 'pages:index' %}">Home</a>
    </li>
    <li class="breadcrumb-item active">Shop</li>
  </ol>
  <!---->
  <!-- banner -->
  <section class="ab-info-main py-md-5 py-4">
    <div class="container py-md-3">
      <!-- top Products -->
      <div class="row">
        <!-- product left -->
        <div class="side-bar col-lg-3">

          {#          <div class="search-bar w3layouts-newsletter">#}
          {#            <h3 class="sear-head">Search Here..</h3>#}
          {#            <form action="#" method="post" class="d-flex">#}
          {#              <input type="search" placeholder="Product name..." name="search"#}
          {#                     class="form-control" required="">#}
          {#              <button class="btn1"><span class="fa fa-search"#}
          {#                                         aria-hidden="true"></span></button>#}
          {#            </form>#}
          {#          </div>#}
          <!--preference -->
          <div class="left-side my-4">
            <h3 class="sear-head d-flex justify-content-between">
              <span>Categories</span>
              <span class="text-muted">Filter</span>
            </h3>
            <ul class="w3layouts-box-list">
              {% for category in categories %}
                <li

                >
                  <a href="{% url 'pages:shop' %}?category={{ category.id }}"
                      {% if category.id|to_str != request.GET.category %}
                     class="text-muted"
                      {% endif %}
                  >
                    <span
                        class="span text-capitalize">{{ category.category_name }}</span>
                  </a>
                </li>
              {% endfor %}

            </ul>
          </div>
          <!-- // preference -->
        </div>
        <!-- //product left
        product right -->
        <div class="left-ads-display col-lg-9">
          <div class="row">
            {% for product in products %}
              <div class="col-md-4 product-men">
                <div class="product-shoe-info shoe text-center">
                  <div class="men-thumb-item">
                    {% if product.image %}
                      <a href="{% url 'pages:item_detail' product.id %}">
                        <img src='{{ product.image.url }}' class="img-fluid"
                             alt="">
                      </a>
                    {% endif %}
                  </div>
                  <div class="item-info-product">
                    <h4>
                      <a href="{% url 'pages:item_detail' product.id %}"
                      >{{ product.name }}</a>
                    </h4>

                    <div class="product_price">
                      <div class="grid-price text-center mb-1">
                        <span class="money">Rs. {{ product.price }}</span>
                      </div>
                      <div class="btn-group">
                        <a href="{% url 'pages:item_detail' product.id %}"
                           class="fancy-button secondary mr-1">View</a>
                        <a href="{% url 'pages:buy' product.id %}#fill-details"
                           class="fancy-button">Buy</a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            {% endfor %}
            <div class="col-md-4 offset-md-8">
              <!-- pagination -->
              <div class="btn-group mt-3 float-right">
                <a
                    class="btn text-white btn-primary {% if not products.has_previous %} disabled {% endif %}"
                    {% if products.has_previous %}
                    href="?page={{ products.previous_page_number }}&&category={{ request.GET.category }}"
                    {% endif %}
                >Previous</a
                >
                <a
                    class="btn text-white btn-primary {% if not products.has_next %} disabled {% endif %}"
                    {% if products.has_next %}
                    href="?page={{ products.next_page_number }}&&category={{ request.GET.category }}"
                    {% endif %}
                >Next</a
                >
              </div>

              <!-- // pagination -->
            </div>
          </div>
          <div class="grid-img-right mt-4 text-right">
            <span class="money">Flat 50% Off</span>
            <a href="{% url 'pages:shop' %}" class="btn">Shop Now</a>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- //contact -->
  {% include 'pages/utils/footer.html' %}
  <script>
      addEventListener("load", function () {
          setTimeout(hideURLbar, 0);
      }, false);

      function hideURLbar() {
          window.scrollTo(0, 1);
      }
  </script>
{% endblock content %}